[supabase]
url = "https://mvrdowfzsidxgdczcccrh.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cmRvd2Z6c2lkeGdkY3pjY3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0Njk0MjIsImV4cCI6MjEwNzA0NTQyMn0.ibu0WZsYyCs7tWUzZkhdjFV8JOTH8U69arR_ObeA_HU" 
